# Generated by Django 6.0 on 2026-01-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_note_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
